# WARNING - DO NOT EDIT - YOUR CHANGES WILL NOT BE PROTECTED.
# This file is auto-generated by the aac gen-plugin and may be overwritten.


Feature: Ensure the LSP server starts in TCP mode.

  Scenario: Start the LSP server in TCP mode.
  
      Given The LSP server is not currently running.
      When The aac application is run with the start-lsp-tcp command.
      Then The aac application is run with the start-lsp-tcp command.
      
    
  
  